// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxxltuasdtjigtcmjzqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4eGx0dWFzZHRqaWd0Y21qenFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjk1ODYsImV4cCI6MjA2NTg0NTU4Nn0.q-9jwILTuGdB2-zjwha15ESju9DiwKt7eW6vluxLR7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);